# --- Kafka reactive messaging channels ---
mp.messaging.incoming.validation-requests.connector=smallrye-kafka
mp.messaging.incoming.validation-requests.topic=blog-validation-request
mp.messaging.incoming.validation-requests.auto.offset.reset=earliest

mp.messaging.outgoing.validation-responses.connector=smallrye-kafka
mp.messaging.outgoing.validation-responses.topic=blog-validation-response

quarkus.http.port=8081
