############################
# HTTP
############################
quarkus.http.host=0.0.0.0
quarkus.http.port=8081

############################
# KAFKA / REDPANDA
############################
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}

############################
# INCOMING (Requests)
############################
mp.messaging.incoming.validation-requests.connector=smallrye-kafka
mp.messaging.incoming.validation-requests.topic=blog-validation-request
mp.messaging.incoming.validation-requests.auto.offset.reset=earliest

############################
# OUTGOING (Responses)
############################
mp.messaging.outgoing.validation-responses.connector=smallrye-kafka
mp.messaging.outgoing.validation-responses.topic=blog-validation-response

############################
# OPTIONAL: LOGGING
############################
quarkus.log.level=INFO