# HTTP
quarkus.http.port=8080
quarkus.http.host=0.0.0.0

# Datasource (via env vars)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_JDBC_URL}

# Hibernate
quarkus.hibernate-orm.database.generation=update

# Kafka (via env var)
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}

# Reactive Messaging Kafka (string payload)
mp.messaging.outgoing.validation-requests.connector=smallrye-kafka
mp.messaging.outgoing.validation-requests.topic=blog-validation-request
mp.messaging.outgoing.validation-requests.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.incoming.validation-responses.connector=smallrye-kafka
mp.messaging.incoming.validation-responses.topic=blog-validation-response
mp.messaging.incoming.validation-responses.auto.offset.reset=earliest
mp.messaging.incoming.validation-responses.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Optional: health endpoints (nice for containers)
quarkus.smallrye-health.root-path=/q/health