# --- Kafka reactive messaging channels ---
mp.messaging.outgoing.validation-requests.connector=smallrye-kafka
mp.messaging.outgoing.validation-requests.topic=blog-validation-request

mp.messaging.incoming.validation-responses.connector=smallrye-kafka
mp.messaging.incoming.validation-responses.topic=blog-validation-response
mp.messaging.incoming.validation-responses.auto.offset.reset=earliest

# ensure string payloads for kafka
mp.messaging.outgoing.validation-requests.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.validation-responses.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=update