############################
# HTTP
############################
quarkus.http.host=0.0.0.0
quarkus.http.port=8080

############################
# DATASOURCE (MySQL)
############################
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${DB_JDBC_URL}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

quarkus.datasource.jdbc.max-size=16

############################
# HIBERNATE
############################
quarkus.hibernate-orm.database.generation=update

############################
# KAFKA / REDPANDA
############################
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}

############################
# OUTGOING VALIDATION REQUEST
############################
mp.messaging.outgoing.validation-requests.connector=smallrye-kafka
mp.messaging.outgoing.validation-requests.topic=blog-validation-request
mp.messaging.outgoing.validation-requests.value.serializer=org.apache.kafka.common.serialization.StringSerializer

############################
# INCOMING VALIDATION RESPONSE
############################
mp.messaging.incoming.validation-responses.connector=smallrye-kafka
mp.messaging.incoming.validation-responses.topic=blog-validation-response
mp.messaging.incoming.validation-responses.auto.offset.reset=earliest
mp.messaging.incoming.validation-responses.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer